datagrid:
    email-notification-grid:
        options:
            entityHint: transactional email
        source:
            acl_resource: oro_notification_emailnotification_view
            type: orm
            query:
                select:
                    - e
                    - event.name as eventName
                    - recipientList.owner as ownerRecipient
                    - recipientList.email as emailRecipient
                    - template.name as templateName
                from:
                    - { table: OroNotificationBundle:EmailNotification, alias: e }
                join:
                    left:
                        - { join: e.event, alias: event }
                        - { join: e.template, alias: template }
                        - { join: e.recipientList, alias: recipientList }
                        - { join: recipientList.users, alias: recipientUsersList }
                        - { join: recipientList.groups, alias: recipientGroupsList }

        columns:
            entityName:
                label: oro.notification.datagrid.entity_name
                data_name: entityName
                type: twig
                template: OroNotificationBundle:EmailNotification:Datagrid/Property/entityName.html.twig
                frontend_type: html
                choices: @oro_notification.event_listener.email_notification_service->getEntityNameChoices

            eventName:
                type: translateable
                label: oro.notification.datagrid.event_name
                choices: @oro_notification.event_listener.email_notification_service->getEventNameChoices

            templateName:
                label: oro.notification.datagrid.template

            recipientUsersList:
                type: twig
                template: OroNotificationBundle:EmailNotification:Datagrid/Property/recipientUsersList.html.twig
                label: oro.notification.datagrid.recipient.user
                frontend_type: html

            recipientGroupsList:
                type: twig
                label: oro.notification.datagrid.recipient.group
                template: OroNotificationBundle:EmailNotification:Datagrid/Property/recipientGroupsList.html.twig
                choices: @oro_notification.event_listener.email_notification_service->getRecipientGroupsChoices
                frontend_type: html

            emailRecipient:
                label: oro.notification.datagrid.recipient.custom_email
                frontend_type: string

            ownerRecipient:
                label: oro.notification.datagrid.recipient.owner
                frontend_type: boolean

        properties:
            id: ~
            update_link:
                type: url
                route: oro_notification_emailnotification_update
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_emailnotication
                params:
                    - id
        actions:
            update:
                type: navigate
                label: Update
                acl_resource: oro_notification_emailnotification_update
                icon: edit
                link: update_link
                rowAction: true
            delete:
                type: delete
                label: Delete
                acl_resource: oro_notification_emailnotification_remove
                icon: trash
                link: delete_link

        sorters: ~

        filters:
            columns:
                entityName:
                    type: choice
                    data_name: e.entityName
                    options:
                        translation_domain: config
                        field_options:
                            multiple: true
                            choices: @oro_notification.event_listener.email_notification_service->getEntityNameChoices

                eventName:
                    type: choice
                    data_name: eventName
                    options:
                        field_options:
                            multiple: true
                            choices: @oro_notification.event_listener.email_notification_service->getEventNameChoices

                templateName:
                    type: string
                    data_name: template.name

                recipientUsersList:
                    type: choice
                    data_name: recipientUsersList
                    options:
                        field_options:
                            multiple: true
                            choices: @oro_notification.event_listener.email_notification_service->getRecipientUsersChoices

                recipientGroupsList:
                    type: choice
                    data_name: recipientGroupsList
                    options:
                        field_options:
                            multiple: true
                            choices: @oro_notification.event_listener.email_notification_service->getRecipientGroupsChoices

                emailRecipient:
                    type: string
                    data_name: emailRecipient

                ownerRecipient:
                    type: boolean
                    data_name: ownerRecipient
