parameters:
    oro_navigation.emailnotification.datagrid_manager.class: Oro\Bundle\NotificationBundle\Datagrid\EmailNotificationDatagridManager

services:
    oro_navigation.emailnotification.datagrid_manager:
        class: %orocrm_account.account.datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: emailnotification
              entity_name: %oro_navigation.emailnotification.datagrid_manager.class%
              entity_hint: emailnotification
              flexible: false
              route_name: oro_notification_emailnotification_index
