oro_menu_config:
    items:
        oro_notification_emailnotification_list:
            label: 'Notifications'
            route: 'oro_notification_emailnotification_index'
            extras:
                routes: ['oro_notification_emailnotification_*']
    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        emails:
                            children:
                                oro_notification_emailnotification_list: ~

oro_titles:
    oro_notification_emailnotification_index: ~
    oro_notification_emailnotification_update: "Edit Notification Rule #%%id%%"
    oro_notification_emailnotification_create: "Add Notification Rule"
