parameters:
    oro_navigation.emailnotification.entity.class: Oro\Bundle\NotificationBundle\Entity\EmailNotification
    oro_notification.event_names.extractor.class: Oro\Bundle\NotificationBundle\Provider\EventNamesExtractor

    oro_notification.email_notification.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_notification.form.type.email_notification.api.class: Oro\Bundle\NotificationBundle\Form\Type\EmailNotificationApiType
    oro_notification.form.handler.email_notification.api.class:

services:
    oro_notification.event_names.extractor:
        class: %oro_notification.event_names.extractor.class%
        arguments:
            - @kernel
        tags:
            - { name: translation.extractor, alias: notification_event_names_extractor }

    # Email notification API
    oro_notification.email_notification.manager.api:
        class: %oro_notification.email_notification.manager.api.class%
        arguments:
            - %oro_navigation.emailnotification.entity.class%
            - @doctrine.orm.entity_manager

    oro_notification.form.type.email_notification.api:
        class: %oro_notification.form.type.email_notification.api.class%
        tags:
            - { name: form.type, alias: emailnotification }

    oro_notification.form.email_notification.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["emailnotification", "emailnotification", null]

    oro_notification.form.handler.email_notification.api:
        class: %oro_notification.form.handler.email_notification.api.class%
        scope: request
        arguments:
            - @oro_notification.form.email_notification.api
            - @request
            - @doctrine.orm.entity_manager
