parameters:
    oro_navigation.emailnotification.entity.class: Oro\Bundle\NotificationBundle\Entity\EmailNotification
    oro_notification.event_names.extractor.class: Oro\Bundle\NotificationBundle\Provider\EventNamesExtractor

services:
    oro_notification.event_names.extractor:
        class: %oro_notification.event_names.extractor.class%
        arguments:
        tags:
            - { name: translation.extractor, alias: notification_event_names_extractor }
