parameters:
    oro_notification.event_names.extractor.class: Oro\Bundle\NotificationBundle\Event\EventNamesExtractor

services:
    oro_notification.event_names.extractor:
        class: %oro_notification.translation.extractor.class%
        arguments:
        tags:
            - { name: translation.extractor, alias: notification_event_names_extractor }