oro_system_configuration:
    fields:
        oro_notification.languages:
            type: oro_locale
            priority: 35
            options:
                label: 'Email templates languages'
                tooltip: oro.notification.form.tooltip.languages
                required: true
                multiple: true
                constraints:
                    - NotBlank: ~


    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            localization:
                                children:
                                    locale_settings:
                                        children:
                                            - oro_notification.languages
