Oro\Bundle\NotificationBundle\Entity\EmailNotification:
    properties:
        event:
            - NotBlank: ~
        template:
            - NotBlank: ~
        entityName:
            - NotBlank: ~
#        template:
#            - NotBlank: ~
