Oro\Bundle\NotificationBundle\Entity\EmailNotification:
    properties:
        event:
            - NotBlank: ~
        template:
            - NotBlank: ~
        entityName:
            - NotBlank: ~

Oro\Bundle\NotificationBundle\Entity\RecipientList:
    constraints:
        - Callback:
            methods:   [isValid]
